document.writeln("<link rel=\'stylesheet\' href=\'https://unpkg.com/element-ui/lib/theme-chalk/index.css\'>");
document.writeln("");
document.writeln("<script src=\'https://unpkg.com/vue/dist/vue.js\'></script>");
document.writeln("<script src=\'https://unpkg.com/element-ui@2.15.6/lib/index.js\'></script>");
document.writeln("");
document.writeln("<div id=\'app\'>");
document.writeln("<template>");
document.writeln("  <el-select v-model=\'value\' placeholder=\'请选择\' style=\'width: 320px;\'>");
document.writeln("    <el-option");
document.writeln("      v-for=\'item in options\'");
document.writeln("      :key=\'item.value\'");
document.writeln("      :label=\'item.label\'");
document.writeln("      :value=\'item.value\'>");
document.writeln("    </el-option>");
document.writeln("  </el-select>");
document.writeln("</template>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("var Main = {");
document.writeln("    data() {");
document.writeln("      return {");
document.writeln("        options: [ {          value: \'选项1\',          label: \'黄金糕\',          disabled: false        }, {          value: \'选项2\',          label: \'双皮奶\',          disabled: true        }, {          value: \'选项3\',          label: \'蚵仔煎\',          disabled: false        }, {          value: \'选项4\',          label: \'龙须面\',          disabled: false        },],");
document.writeln("        value: \'\'");
document.writeln("      }");
document.writeln("    }");
document.writeln("  }");
document.writeln("var Ctor = Vue.extend(Main)");
document.writeln("new Ctor().$mount(\'#app\')");
document.writeln("</script>");
document.writeln("");
